### ISSUE TITLE
SignUp in newemp.html leads nowhere.

### ISSUE THREAD

**Issue by samseen** [SigmaVEC/PayRollManager#3]
I noticed nothing happens after signing up a new employee from newemp.html. On digging in further, newemp.html has unclosed div tags and the form isn't handled by any controller. The form tags doesn't also match any elements declared in the controller. Can you please help look into these ?

**PS: I can't understand why the sql query to generate the table was completely removed in the last commit. Any major reason?**

**Comment by RahulSriram** [comment]
@samseen 
This project is unfinished and needs to be treated as such. Having said that, there have been a lot of redundant copies of functionality in both the Controllers and html side.

I have fixed most of the issues, if not all on the controllers, and I have asked @Shivakishore14 to look into this issue for html files, and resolve it.

As for the sql file, it was never supposed to be there, and it was an error on our part.
I can now see how it will help others like you to get up and running for the database part, and I'll update the file with the latest table structure.

Thank you for your interest in our project, and if you want to help us fix the bugs, you are welcome to do so.

EDIT: Commit bac72dff810431121b8e34fcafa157784e69b5d1 adds the table

**Comment by RahulSriram** [comment]
@csaranbalaji , let this issue be open until all redundant copies of files are removed
